"use client"

import { useState } from "react"
import { zodResolver } from "@hookform/resolvers/zod"
import { useForm } from "react-hook-form"
import { z } from "zod"
import { Apple, ArrowRight, Loader2 } from "lucide-react"

import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Form, FormControl, FormDescription, FormField, FormItem, FormLabel, FormMessage } from "@/components/ui/form"
import { Input } from "@/components/ui/input"
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Textarea } from "@/components/ui/textarea"
import { generateCaloriePlan } from "@/app/calorie-actions"
import { CalorieResults } from "@/components/calorie-results"

const formSchema = z.object({
  age: z.coerce.number().min(13, "Age must be at least 13").max(120, "Age must be less than 120"),
  gender: z.enum(["male", "female", "other"]),
  height: z.coerce.number().min(100, "Height must be at least 100cm").max(250, "Height must be less than 250cm"),
  weight: z.coerce.number().min(30, "Weight must be at least 30kg").max(300, "Weight must be less than 300kg"),
  activityLevel: z.enum(["sedentary", "lightlyActive", "moderatelyActive", "veryActive", "extremelyActive"]),
  goal: z.enum(["lose", "maintain", "gain"]),
  dietaryPreferences: z.string().optional(),
  mealsPerDay: z.coerce.number().min(2, "At least 2 meals").max(8, "Maximum 8 meals"),
})

export type CalorieFormData = z.infer<typeof formSchema>

export function CalorieForm() {
  const [isLoading, setIsLoading] = useState(false)
  const [caloriePlan, setCaloriePlan] = useState<string | null>(null)

  const form = useForm<z.infer<typeof formSchema>>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      age: 25,
      gender: undefined,
      height: 170,
      weight: 70,
      activityLevel: "moderatelyActive",
      goal: "maintain",
      dietaryPreferences: "",
      mealsPerDay: 3,
    },
  })

  async function onSubmit(values: z.infer<typeof formSchema>) {
    setIsLoading(true)
    try {
      const plan = await generateCaloriePlan(values)
      setCaloriePlan(plan)
    } catch (error) {
      console.error("Error generating calorie plan:", error)
    } finally {
      setIsLoading(false)
    }
  }

  function handleReset() {
    setCaloriePlan(null)
    form.reset()
  }

  if (caloriePlan) {
    return <CalorieResults caloriePlan={caloriePlan} onReset={handleReset} />
  }

  return (
    <Card className="w-full bg-zinc-900/80 border border-zinc-800 shadow-2xl backdrop-blur-md rounded-2xl text-white font-sans" style={{ boxShadow: '0 4px 32px 0 rgba(16, 185, 129, 0.10), 0 1.5px 12px 0 rgba(16, 185, 129, 0.10)' }}>
      <CardHeader>
        <CardTitle className="flex items-center gap-2 text-white drop-shadow-lg" style={{ fontFamily: 'Inter, system-ui, sans-serif' }}>
          <Apple className="h-6 w-6 text-emerald-400" />
          <span>Create Your Calorie Plan</span>
        </CardTitle>
        <CardDescription className="text-zinc-300">Fill in your details to get a personalized nutrition plan generated by AI.</CardDescription>
      </CardHeader>
      <CardContent>
        <Form {...form}>
          <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-6">
            <div className="grid gap-6 sm:grid-cols-2">
              <FormField
                control={form.control}
                name="age"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Age</FormLabel>
                    <FormControl>
                      <Input type="number" {...field} className="bg-zinc-900 text-white border border-zinc-700 placeholder:text-zinc-400 focus:ring-emerald-500 focus:border-emerald-500" />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />

              <FormField
                control={form.control}
                name="gender"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Gender</FormLabel>
                    <Select onValueChange={field.onChange} defaultValue={field.value}>
                      <FormControl>
                        <SelectTrigger className="bg-zinc-900 text-white border border-zinc-700 placeholder:text-zinc-400 focus:ring-emerald-500 focus:border-emerald-500">
                          <SelectValue placeholder="Select gender" />
                        </SelectTrigger>
                      </FormControl>
                      <SelectContent className="bg-zinc-900 text-white border border-zinc-700">
                        <SelectItem value="male">Male</SelectItem>
                        <SelectItem value="female">Female</SelectItem>
                        <SelectItem value="other">Other</SelectItem>
                      </SelectContent>
                    </Select>
                    <FormMessage />
                  </FormItem>
                )}
              />
            </div>

            <div className="grid gap-6 sm:grid-cols-2">
              <FormField
                control={form.control}
                name="height"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Height (cm)</FormLabel>
                    <FormControl>
                      <Input type="number" {...field} className="bg-zinc-900 text-white border border-zinc-700 placeholder:text-zinc-400 focus:ring-emerald-500 focus:border-emerald-500" />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />

              <FormField
                control={form.control}
                name="weight"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Weight (kg)</FormLabel>
                    <FormControl>
                      <Input type="number" {...field} className="bg-zinc-900 text-white border border-zinc-700 placeholder:text-zinc-400 focus:ring-emerald-500 focus:border-emerald-500" />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
            </div>

            <FormField
              control={form.control}
              name="activityLevel"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Activity Level</FormLabel>
                  <Select onValueChange={field.onChange} defaultValue={field.value}>
                    <FormControl>
                      <SelectTrigger className="bg-zinc-900 text-white border border-zinc-700 placeholder:text-zinc-400 focus:ring-emerald-500 focus:border-emerald-500">
                        <SelectValue placeholder="Select activity level" />
                      </SelectTrigger>
                    </FormControl>
                    <SelectContent className="bg-zinc-900 text-white border border-zinc-700">
                      <SelectItem value="sedentary">Sedentary (little to no exercise)</SelectItem>
                      <SelectItem value="lightlyActive">Lightly Active (1-3 days/week)</SelectItem>
                      <SelectItem value="moderatelyActive">Moderately Active (3-5 days/week)</SelectItem>
                      <SelectItem value="veryActive">Very Active (6-7 days/week)</SelectItem>
                      <SelectItem value="extremelyActive">Extremely Active (physical job/training 2x day)</SelectItem>
                    </SelectContent>
                  </Select>
                  <FormMessage />
                </FormItem>
              )}
            />

            <FormField
              control={form.control}
              name="goal"
              render={({ field }) => (
                <FormItem className="space-y-3">
                  <FormLabel>Primary Goal</FormLabel>
                  <FormControl>
                    <RadioGroup
                      onValueChange={field.onChange}
                      value={field.value || ""}
                      className="flex flex-col space-y-1 sm:flex-row sm:space-y-0 sm:space-x-4"
                    >
                      <FormItem className="flex items-center space-x-3 space-y-0">
                        <FormControl>
                          <RadioGroupItem
                            value="lose"
                            id="lose"
                            className="data-[state=checked]:bg-emerald-500 data-[state=checked]:border-emerald-500"
                          />
                        </FormControl>
                        <FormLabel
                          htmlFor="lose"
                          className="font-normal cursor-pointer"
                        >
                          Lose Weight
                        </FormLabel>
                      </FormItem>
                      <FormItem className="flex items-center space-x-3 space-y-0">
                        <FormControl>
                          <RadioGroupItem
                            value="maintain"
                            id="maintain"
                            className="data-[state=checked]:bg-emerald-500 data-[state=checked]:border-emerald-500"
                          />
                        </FormControl>
                        <FormLabel
                          htmlFor="maintain"
                          className="font-normal cursor-pointer"
                        >
                          Maintain Weight
                        </FormLabel>
                      </FormItem>
                      <FormItem className="flex items-center space-x-3 space-y-0">
                        <FormControl>
                          <RadioGroupItem
                            value="gain"
                            id="gain"
                            className="data-[state=checked]:bg-emerald-500 data-[state=checked]:border-emerald-500"
                          />
                        </FormControl>
                        <FormLabel
                          htmlFor="gain"
                          className="font-normal cursor-pointer"
                        >
                          Gain Weight/Muscle
                        </FormLabel>
                      </FormItem>
                    </RadioGroup>
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />

            <FormField
              control={form.control}
              name="mealsPerDay"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Meals Per Day</FormLabel>
                  <Select onValueChange={(val) => field.onChange(Number(val))} defaultValue={String(field.value)}>
                    <FormControl>
                      <SelectTrigger className="bg-zinc-900 text-white border border-zinc-700 placeholder:text-zinc-400 focus:ring-emerald-500 focus:border-emerald-500">
                        <SelectValue placeholder="Select meals per day" />
                      </SelectTrigger>
                    </FormControl>
                    <SelectContent className="bg-zinc-900 text-white border border-zinc-700">
                      <SelectItem value="2">2 meals</SelectItem>
                      <SelectItem value="3">3 meals</SelectItem>
                      <SelectItem value="4">4 meals</SelectItem>
                      <SelectItem value="5">5 meals</SelectItem>
                      <SelectItem value="6">6 meals</SelectItem>
                    </SelectContent>
                  </Select>
                  <FormMessage />
                </FormItem>
              )}
            />

            <FormField
              control={form.control}
              name="dietaryPreferences"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Dietary Preferences (Optional)</FormLabel>
                  <FormControl>
                    <Textarea
                      placeholder="E.g., vegetarian, vegan, gluten-free, dairy-free, allergies, food preferences..."
                      className="resize-none bg-zinc-900 text-white border border-zinc-700 placeholder:text-zinc-400 focus:ring-emerald-500 focus:border-emerald-500"
                      {...field}
                    />
                  </FormControl>
                  <FormDescription className="text-zinc-200">
                    Specify any dietary restrictions or preferences for a customized meal plan.
                  </FormDescription>
                  <FormMessage />
                </FormItem>
              )}
            />

            <Button
              type="submit"
              className="w-full bg-gradient-to-r from-emerald-500 to-teal-500 text-white font-bold shadow-lg hover:brightness-110 transition"
              disabled={isLoading}
            >
              {isLoading ? (
                <>
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  Generating Plan...
                </>
              ) : (
                <>
                  Generate Calorie Plan
                  <ArrowRight className="ml-2 h-4 w-4" />
                </>
              )}
            </Button>
          </form>
        </Form>
      </CardContent>
    </Card>
  )
}
