"use client"

import { useState } from "react"
import { zodResolver } from "@hookform/resolvers/zod"
import { useForm } from "react-hook-form"
import { z } from "zod"
import { Dumbbell, ArrowRight, Loader2 } from "lucide-react"

import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Form, FormControl, FormDescription, FormField, FormItem, FormLabel, FormMessage } from "@/components/ui/form"
import { Input } from "@/components/ui/input"
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Slider } from "@/components/ui/slider"
import { Textarea } from "@/components/ui/textarea"
import { generateWorkoutPlan } from "@/app/actions"
import { WorkoutResults } from "@/components/workout-results"

const formSchema = z.object({
  fitnessLevel: z.enum(["beginner", "intermediate", "advanced"]),
  height: z.coerce.number().min(100, "Height must be at least 100cm").max(250, "Height must be less than 250cm"),
  weight: z.coerce.number().min(30, "Weight must be at least 30kg").max(250, "Weight must be less than 250kg"),
  goalWeight: z.coerce
    .number()
    .min(30, "Goal weight must be at least 30kg")
    .max(250, "Goal weight must be less than 250kg"),
  workoutDays: z.coerce.number().min(1, "Must work out at least 1 day").max(7, "Cannot exceed 7 days"),
  gymGoal: z.enum(["loseWeight", "buildMuscle", "improveEndurance", "increaseStrength"]),
  additionalInfo: z.string().optional(),
})

export type FitnessFormData = z.infer<typeof formSchema>

export function FitnessForm() {
  const [isLoading, setIsLoading] = useState(false)
  const [workoutPlan, setWorkoutPlan] = useState<string | null>(null)

  const form = useForm<z.infer<typeof formSchema>>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      fitnessLevel: "beginner",
      height: 170,
      weight: 70,
      goalWeight: 70,
      workoutDays: 3,
      gymGoal: "buildMuscle",
      additionalInfo: "",
    },
  })

  async function onSubmit(values: z.infer<typeof formSchema>) {
    setIsLoading(true)
    try {
      const plan = await generateWorkoutPlan(values)
      setWorkoutPlan(plan)
    } catch (error) {
      console.error("Error generating workout plan:", error)
    } finally {
      setIsLoading(false)
    }
  }

  function handleReset() {
    setWorkoutPlan(null)
    form.reset()
  }

  if (workoutPlan) {
    return <WorkoutResults workoutPlan={workoutPlan} onReset={handleReset} />
  }

  return (
    <Card className="w-full bg-zinc-900/80 border border-zinc-800 shadow-2xl backdrop-blur-md rounded-2xl text-white font-sans" style={{ boxShadow: '0 4px 32px 0 rgba(255, 0, 80, 0.10), 0 1.5px 12px 0 rgba(255, 0, 80, 0.10)' }}>
      <CardHeader>
        <CardTitle className="flex items-center gap-2 text-white drop-shadow-lg" style={{ fontFamily: 'Inter, system-ui, sans-serif' }}>
          <Dumbbell className="h-6 w-6 text-emerald-400" />
          <span>Create Your Workout Plan</span>
        </CardTitle>
        <CardDescription className="text-zinc-300">Fill in your details to get a personalized workout routine generated by AI.</CardDescription>
      </CardHeader>
      <CardContent>
        <Form {...form}>
          <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-6">
            <FormField
              control={form.control}
              name="fitnessLevel"
              render={({ field }) => (
                <FormItem className="space-y-3">
                  <FormLabel>Fitness Level</FormLabel>
                  <FormControl>
                    <RadioGroup
                      onValueChange={field.onChange}
                      defaultValue={field.value}
                      className="flex flex-col space-y-1 sm:flex-row sm:space-y-0 sm:space-x-4"
                    >
                      <FormItem className="flex items-center space-x-3 space-y-0">
                        <FormControl>
                          <RadioGroupItem value="beginner" />
                        </FormControl>
                        <FormLabel className="font-normal">Beginner</FormLabel>
                      </FormItem>
                      <FormItem className="flex items-center space-x-3 space-y-0">
                        <FormControl>
                          <RadioGroupItem value="intermediate" />
                        </FormControl>
                        <FormLabel className="font-normal">Intermediate</FormLabel>
                      </FormItem>
                      <FormItem className="flex items-center space-x-3 space-y-0">
                        <FormControl>
                          <RadioGroupItem value="advanced" />
                        </FormControl>
                        <FormLabel className="font-normal">Advanced</FormLabel>
                      </FormItem>
                    </RadioGroup>
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />

            <div className="grid gap-6 sm:grid-cols-2">
              <FormField
                control={form.control}
                name="height"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Height (cm)</FormLabel>
                    <FormControl>
                      <Input type="number" {...field} className="bg-zinc-900 text-white border border-zinc-700 placeholder:text-zinc-400 focus:ring-orange-500 focus:border-orange-500" />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />

              <FormField
                control={form.control}
                name="weight"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Current Weight (kg)</FormLabel>
                    <FormControl>
                      <Input type="number" {...field} className="bg-zinc-900 text-white border border-zinc-700 placeholder:text-zinc-400 focus:ring-orange-500 focus:border-orange-500" />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
            </div>

            <FormField
              control={form.control}
              name="goalWeight"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Goal Weight (kg)</FormLabel>
                  <FormControl>
                    <Input type="number" {...field} className="bg-zinc-900 text-white border border-zinc-700 placeholder:text-zinc-400 focus:ring-orange-500 focus:border-orange-500" />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />

            <FormField
              control={form.control}
              name="workoutDays"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Workout Days Per Week: {field.value}</FormLabel>
                  <FormControl>
                    <Slider
                      min={1}
                      max={7}
                      step={1}
                      defaultValue={[field.value]}
                      onValueChange={(vals) => field.onChange(vals[0])}
                      className="py-4 custom-slider-orange"
                    />
                  </FormControl>
                  <FormDescription className="text-zinc-200">How many days can you commit to working out?</FormDescription>
                  <FormMessage />
                </FormItem>
              )}
            />

            <FormField
              control={form.control}
              name="gymGoal"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Primary Goal</FormLabel>
                  <Select onValueChange={field.onChange} defaultValue={field.value}>
                    <FormControl>
                      <SelectTrigger className="bg-zinc-900 text-white border border-zinc-700 placeholder:text-zinc-400 focus:ring-orange-500 focus:border-orange-500">
                        <SelectValue placeholder="Select your primary fitness goal" />
                      </SelectTrigger>
                    </FormControl>
                    <SelectContent className="bg-zinc-900 text-white border border-zinc-700">
                      <SelectItem value="loseWeight">Lose Weight</SelectItem>
                      <SelectItem value="buildMuscle">Build Muscle</SelectItem>
                      <SelectItem value="improveEndurance">Improve Endurance</SelectItem>
                      <SelectItem value="increaseStrength">Increase Strength</SelectItem>
                    </SelectContent>
                  </Select>
                  <FormMessage />
                </FormItem>
              )}
            />

            <FormField
              control={form.control}
              name="additionalInfo"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Additional Information (Optional)</FormLabel>
                  <FormControl>
                    <Textarea
                      placeholder="Any injuries, preferences, or specific goals you'd like to mention"
                      className="resize-none bg-zinc-900 text-white border border-zinc-700 placeholder:text-zinc-400 focus:ring-orange-500 focus:border-orange-500"
                      {...field}
                    />
                  </FormControl>
                  <FormDescription className="text-zinc-200">
                    Include any relevant information that might help create a better workout plan for you.
                  </FormDescription>
                  <FormMessage />
                </FormItem>
              )}
            />

            <Button
              type="submit"
              className="w-full bg-gradient-to-r from-orange-500 to-rose-500 text-white font-bold shadow-lg hover:brightness-110 transition"
              disabled={isLoading}
            >
              {isLoading ? (
                <>
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  Generating Plan...
                </>
              ) : (
                <>
                  Generate Workout Plan
                  <ArrowRight className="ml-2 h-4 w-4" />
                </>
              )}
            </Button>
          </form>
        </Form>
      </CardContent>
    </Card>
  )
}
